"""
predict.py - Next-day prediction with Strategy 4 gate logic

Strategy 4 Gate Logic:
  Step 1: Strategy 4 checks if today is worth entering
          Buy  gate: EMA bullish AND close above BB upper
          Sell gate: EMA bearish OR  close below BB lower
  Step 2: Only if buy gate is open, LSTM makes final decision
          LSTM says up   -> BUY
          LSTM says down -> WAIT (signal exists but LSTM disagrees)
  Step 3: If sell gate is open -> SELL / STAY OUT

Usage:
  python predict.py               <- use ticker from training
  python predict.py 2454.TW       <- specify ticker

Requires models/ folder generated by train.py
"""

import warnings, os, json, sys
warnings.filterwarnings("ignore")

import yfinance as yf

import data_loader
import lstm_model
import arima_model
import stacking

MODEL_DIR = "models"


def load_config() -> dict:
    path = os.path.join(MODEL_DIR, "meta.json")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing {path} - please run train.py first!")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def strategy4_gate(signal_buy: int,
                   signal_sell: int,
                   lstm_pred: int,
                   lstm_prob: float,
                   arima_pred: int,
                   stack_pred: int,
                   stack_prob: float) -> dict:
    """
    Apply Strategy 4 gate logic to model predictions.

    Gate rules:
      SELL gate (highest priority):
        - EMA bearish OR close below BB lower
        - Regardless of model predictions -> do not enter

      BUY gate:
        - EMA bullish AND close above BB upper
        - Only then ask LSTM/Stacking for final decision

      NO signal:
        - Hold current position or stay out

    Returns dict with:
      action      : "BUY" / "SELL" / "WAIT" / "HOLD"
      reason      : explanation string
      confidence  : confidence level string
    """

    # ── SELL gate (highest priority) ─────────────────────
    if signal_sell == 1:
        return {
            "action"    : "SELL / STAY OUT",
            "reason"    : "Strategy 4 sell signal triggered\n"
                          "  (EMA bearish OR price below BB lower)\n"
                          "  -> Do not enter, exit if holding",
            "confidence": "Rule-based (Strategy 4)",
        }

    # ── BUY gate ──────────────────────────────────────────
    if signal_buy == 1:
        # Strategy 4 says conditions are right, ask LSTM for final call
        if stack_pred == 1:
            if stack_prob >= 0.65:
                conf = "High   (Strategy 4 + Stacking agree, prob>65%)"
            else:
                conf = "Medium (Strategy 4 triggered, Stacking mildly agrees)"
            return {
                "action"    : "BUY",
                "reason"    : f"Strategy 4 buy signal triggered\n"
                              f"  (EMA bullish AND price above BB upper)\n"
                              f"  Stacking confirms: UP (prob={stack_prob:.2%})\n"
                              f"  LSTM={'+' if lstm_pred==1 else '-'}  "
                              f"ARIMA={'+' if arima_pred==1 else '-'}",
                "confidence": conf,
            }
        else:
            return {
                "action"    : "WAIT",
                "reason"    : f"Strategy 4 buy signal triggered\n"
                              f"  (EMA bullish AND price above BB upper)\n"
                              f"  BUT Stacking disagrees: DOWN (prob={stack_prob:.2%})\n"
                              f"  -> Strategy 4 says enter, models say no\n"
                              f"  -> Safer to wait",
                "confidence": "Low (conflicting signals)",
            }

    # ── No signal ─────────────────────────────────────────
    # Neither buy nor sell gate triggered
    # Use model predictions as reference only
    if stack_pred == 1 and stack_prob >= 0.60:
        ref = f"Models lean UP (prob={stack_prob:.2%}) but no Strategy 4 signal"
    elif stack_pred == 0 and stack_prob <= 0.40:
        ref = f"Models lean DOWN (prob={stack_prob:.2%}) but no Strategy 4 signal"
    else:
        ref = f"Models inconclusive (prob={stack_prob:.2%})"

    return {
        "action"    : "HOLD / OBSERVE",
        "reason"    : f"No Strategy 4 signal today\n"
                      f"  (price within Bollinger Band, trend unclear)\n"
                      f"  {ref}",
        "confidence": "N/A (no signal)",
    }


def main():
    ticker_arg = sys.argv[1] if len(sys.argv) > 1 else None

    print(f"\n{'='*55}")
    print("  Strategy 4 Prediction  (predict.py)")
    print(f"{'='*55}")

    # Load config and models
    meta              = load_config()
    model, scaler     = lstm_model.load(MODEL_DIR)
    arima_meta        = arima_model.load(MODEL_DIR)
    meta_model_loaded = stacking.load(MODEL_DIR)

    print(f"  Ticker    : {meta['ticker']}")
    print(f"  Trained   : {meta['train_start']} ~ {meta['train_end']}")
    print(f"  Saved at  : {meta['saved_at']}")
    print(f"  Threshold : {meta['best_threshold']:.2f}")

    ticker       = ticker_arg if ticker_arg else meta["ticker"]
    feature_cols = meta["feature_cols"]
    seq_len      = meta["seq_len"]
    threshold    = meta["best_threshold"]

    print(f"\n  Target: {ticker}")

    # Download latest data
    raw = yf.download(ticker, period="180d", progress=False)
    raw.dropna(inplace=True)
    if hasattr(raw.columns, 'levels'):
        raw.columns = raw.columns.get_level_values(0)

    df          = data_loader.compute_features(raw)
    close       = df["Close"].squeeze()
    today       = df.index[-1]
    close_today = float(close.iloc[-1])

    # Indicator values
    ema20     = float(df["EMA_20"].iloc[-1])
    ema60     = float(df["EMA_60"].iloc[-1])
    bb_upper  = float(df["BB_upper"].iloc[-1])
    bb_lower  = float(df["BB_lower"].iloc[-1])
    bb_mid    = float(df["BB_mid"].iloc[-1])
    bb_pct    = float(df["BB_pct"].iloc[-1])
    vol_ratio = float(df["VOL_ratio"].iloc[-1])
    trend     = int(df["EMA_trend"].iloc[-1])
    s_buy     = int(df["Signal_buy"].iloc[-1])
    s_sell    = int(df["Signal_sell"].iloc[-1])

    # Model predictions
    lstm_pred,  lstm_prob  = lstm_model.predict(
        model, scaler, df, feature_cols, seq_len, threshold
    )
    arima_pred, arima_fore = arima_model.predict_tomorrow(
        arima_meta, close.tolist(), history_limit=200
    )
    stack_pred, stack_prob = stacking.predict_one_sample(
        meta_model_loaded, lstm_prob, arima_pred
    )

    # Apply Strategy 4 gate logic
    decision = strategy4_gate(
        s_buy, s_sell,
        lstm_pred, lstm_prob,
        arima_pred,
        stack_pred, stack_prob,
    )

    # ── Output ────────────────────────────────────────────
    UP   = "UP   📈"
    DOWN = "DOWN 📉"

    print(f"""
{'='*55}
  Strategy 4 Indicators  [{today.date()}]
{'='*55}
  Ticker        : {ticker}
  Close         : {close_today:.2f} TWD

  -- EMA -----------------------------------------------
  EMA 20        : {ema20:.2f}
  EMA 60        : {ema60:.2f}
  Trend         : {"Bullish (EMA20 > EMA60)" if trend==1 else "Bearish (EMA20 < EMA60)"}

  -- Bollinger Band ------------------------------------
  Upper         : {bb_upper:.2f}
  Mid  (MA20)   : {bb_mid:.2f}
  Lower         : {bb_lower:.2f}
  %B Position   : {bb_pct:.2%}
  Above Upper   : {"Yes -> Buy condition met"  if close_today > bb_upper else "No"}
  Below Lower   : {"Yes -> Sell condition met" if close_today < bb_lower else "No"}

  -- Volume --------------------------------------------
  Vol Ratio     : {vol_ratio:.2f}x  {"Heavy" if vol_ratio>1.5 else "Normal" if vol_ratio>0.7 else "Light"}

  -- Strategy 4 Gate -----------------------------------
  Buy  Gate     : {"OPEN  (EMA bullish + above BB upper)" if s_buy==1  else "CLOSED"}
  Sell Gate     : {"OPEN  (EMA bearish or below BB lower)" if s_sell==1 else "CLOSED"}

{'='*55}
  Model Predictions (reference only)
{'='*55}
  LSTM          : {UP if lstm_pred==1 else DOWN}  (prob={lstm_prob:.2%})
  ARIMA         : {UP if arima_pred==1 else DOWN}  (forecast={arima_fore:.2f})
  Stacking      : {UP if stack_pred==1 else DOWN}  (prob={stack_prob:.2%})

{'='*55}
  Final Decision (Strategy 4 + Stacking)
{'='*55}
  Action        : {decision['action']}
  Reason        :
    {decision['reason']}
  Confidence    : {decision['confidence']}

  Disclaimer: For academic research only. Not investment advice.
{'='*55}
    """)

    return {
        "ticker"     : ticker,
        "date"       : str(today.date()),
        "close"      : close_today,
        "signal_buy" : s_buy,
        "signal_sell": s_sell,
        "lstm_pred"  : lstm_pred,
        "lstm_prob"  : lstm_prob,
        "arima_pred" : arima_pred,
        "arima_fore" : arima_fore,
        "stack_pred" : stack_pred,
        "stack_prob" : stack_prob,
        "action"     : decision["action"],
        "confidence" : decision["confidence"],
    }


if __name__ == "__main__":
    result = main()