"""
predict.py - Next-day prediction with Bollinger Band primary signal

BB Signal Gate Logic (mean reversion):
  Step 1: BB checks if today has a trading signal
          Buy  gate : close <= BB_lower  (price touches lower band → oversold)
          Sell gate : close >= BB_upper  (price touches upper band → overbought)
  Step 2: If buy gate is open, LSTM/Stacking makes final profitability decision
          Stacking says UP   -> BUY   (reversion likely → enter)
          Stacking says DOWN -> WAIT  (reversion may fail → skip)
  Step 3: If sell gate is open → SELL / STAY OUT (overbought, mean reversion down)

Usage:
  python predict.py               <- use ticker from training
  python predict.py 2454.TW       <- specify ticker

Requires models/ folder generated by train.py
"""

import warnings, os, json, sys
warnings.filterwarnings("ignore")

import yfinance as yf

import data_loader
import lstm_model
import arima_model
import stacking

MODEL_DIR = "models"


def load_config() -> dict:
    path = os.path.join(MODEL_DIR, "meta.json")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing {path} - please run train.py first!")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _is_multi_ticker(meta: dict) -> bool:
    """True if model was trained in multi-ticker mode."""
    return meta.get("train_mode", "") == "multi_ticker_bb_weekly"


def bb_signal_gate(signal_buy: int,
                   signal_sell: int,
                   lstm_pred: int,
                   lstm_prob: float,
                   arima_pred: int,
                   stack_pred: int,
                   stack_prob: float,
                   bb_squeeze: int) -> dict:
    """
    Apply Bollinger Band primary signal gate logic to model predictions.

    Gate rules (mean reversion strategy):
      SELL gate (highest priority):
        - close >= BB_upper  → overbought, do not enter long, exit if holding

      BUY gate:
        - close <= BB_lower  → oversold, mean reversion expected
        - Ask LSTM/Stacking: will the reversion succeed?
          Stacking UP   → BUY  (reversion confirmed)
          Stacking DOWN → WAIT (reversion may fail)

      BB SQUEEZE (supplementary):
        - BB_width contracted → potential breakout imminent

      NO signal:
        - Price between bands → market in normal range, observe

    Returns dict with:
      action      : "BUY" / "SELL" / "WAIT" / "HOLD"
      reason      : explanation string
      confidence  : confidence level string
    """

    # ── SELL gate (highest priority) ─────────────────────
    if signal_sell == 1:
        return {
            "action"    : "SELL / STAY OUT",
            "reason"    : "BB sell signal triggered\n"
                          "  (close >= BB upper band → overbought)\n"
                          "  Mean reversion DOWN expected\n"
                          "  -> Exit long / Do not enter",
            "confidence": "Rule-based (BB upper band touch)",
        }

    # ── BUY gate ──────────────────────────────────────────
    if signal_buy == 1:
        squeeze_note = "  [BB Squeeze detected: breakout may amplify move]\n" if bb_squeeze else ""
        # BB oversold confirmed, ask model for profitability prediction
        if stack_pred == 1:
            if stack_prob >= 0.65:
                conf = "High   (BB oversold + Model confirms UP, prob>65%)"
            else:
                conf = "Medium (BB oversold triggered, Model mildly agrees)"
            return {
                "action"    : "BUY",
                "reason"    : f"BB buy signal triggered\n"
                              f"  (close <= BB lower band → oversold)\n"
                              f"{squeeze_note}"
                              f"  Model predicts reversion UP (prob={stack_prob:.2%})\n"
                              f"  LSTM={'+' if lstm_pred==1 else '-'}  "
                              f"ARIMA={'+' if arima_pred==1 else '-'}",
                "confidence": conf,
            }
        else:
            return {
                "action"    : "WAIT",
                "reason"    : f"BB buy signal triggered\n"
                              f"  (close <= BB lower band → oversold)\n"
                              f"{squeeze_note}"
                              f"  BUT Model predicts DOWN (prob={stack_prob:.2%})\n"
                              f"  -> BB says oversold, model says reversion may fail\n"
                              f"  -> Safer to wait for confirmation",
                "confidence": "Low (BB signal vs model conflicting)",
            }

    # ── BB Squeeze only (no band touch) ───────────────────
    if bb_squeeze == 1:
        if stack_pred == 1 and stack_prob >= 0.60:
            ref = f"Squeeze + Model leans UP (prob={stack_prob:.2%})"
        elif stack_pred == 0 and stack_prob <= 0.40:
            ref = f"Squeeze + Model leans DOWN (prob={stack_prob:.2%})"
        else:
            ref = f"Squeeze detected but model inconclusive (prob={stack_prob:.2%})"

        return {
            "action"    : "WATCH",
            "reason"    : f"BB Squeeze detected (volatility contracting)\n"
                          f"  -> No band touch yet, but breakout may be imminent\n"
                          f"  {ref}",
            "confidence": "Low (squeeze only, no signal)",
        }

    # ── No signal ─────────────────────────────────────────
    if stack_pred == 1 and stack_prob >= 0.60:
        ref = f"Model leans UP (prob={stack_prob:.2%}) but no BB signal"
    elif stack_pred == 0 and stack_prob <= 0.40:
        ref = f"Model leans DOWN (prob={stack_prob:.2%}) but no BB signal"
    else:
        ref = f"Model inconclusive (prob={stack_prob:.2%})"

    return {
        "action"    : "HOLD / OBSERVE",
        "reason"    : f"No BB signal today\n"
                      f"  (price inside Bollinger Band, normal range)\n"
                      f"  {ref}",
        "confidence": "N/A (no signal)",
    }


def main():
    ticker_arg = sys.argv[1] if len(sys.argv) > 1 else None

    print(f"\n{'='*55}")
    print("  BB Signal Prediction  (predict.py)")
    print(f"{'='*55}")

    # Load config
    meta     = load_config()
    is_multi = _is_multi_ticker(meta)
    interval = meta.get("interval", "1d")

    print(f"  Train mode : {meta.get('train_mode', 'unknown')}")
    print(f"  Interval   : {interval}")
    print(f"  Trained    : {meta['train_start']} ~ {meta['train_end']}")
    print(f"  Saved at   : {meta['saved_at']}")
    print(f"  Threshold  : {meta['best_threshold']:.2f}")

    # Load models
    model, _ = lstm_model.load(MODEL_DIR)      # model only; scaler loaded per-ticker below
    meta_model_loaded = stacking.load(MODEL_DIR)

    feature_cols = meta["feature_cols"]
    seq_len      = meta["seq_len"]
    threshold    = meta["best_threshold"]

    # Determine ticker
    if is_multi:
        trained_tickers = meta.get("tickers", [])
        if ticker_arg:
            ticker = ticker_arg
        elif trained_tickers:
            ticker = trained_tickers[0]
        else:
            ticker = "2330.TW"
        print(f"  Trained tickers: {trained_tickers}")
        if ticker not in trained_tickers:
            print(f"  WARNING: {ticker} was not in training set. Using first ticker's scaler.")
    else:
        ticker = ticker_arg if ticker_arg else meta.get("ticker", "2330.TW")

    print(f"\n  Target: {ticker}")

    # Load per-ticker scaler
    if is_multi:
        scalers_dict = lstm_model.load_scalers(MODEL_DIR)
        scaler_key   = ticker if ticker in scalers_dict else list(scalers_dict.keys())[0]
        scaler       = scalers_dict[scaler_key]
        print(f"  Scaler loaded for: {scaler_key}")
    else:
        _, scaler = lstm_model.load(MODEL_DIR)

    # Load per-ticker ARIMA
    if is_multi:
        arima_dict = arima_model.load_multi(MODEL_DIR)
        arima_key  = ticker if ticker in arima_dict else list(arima_dict.keys())[0]
        arima_meta = arima_dict[arima_key]
        print(f"  ARIMA loaded for : {arima_key}")
    else:
        arima_meta = arima_model.load(MODEL_DIR)

    # Download latest data (use same interval as training)
    period = "500d" if interval == "1wk" else "180d"
    raw    = yf.download(ticker, period=period, interval=interval, progress=False)
    raw.dropna(inplace=True)
    if hasattr(raw.columns, 'levels'):
        raw.columns = raw.columns.get_level_values(0)

    df          = data_loader.compute_features(raw)
    close       = df["Close"].squeeze()
    today       = df.index[-1]
    close_today = float(close.iloc[-1])

    # Indicator values
    ema20      = float(df["EMA_20"].iloc[-1])
    ema60      = float(df["EMA_60"].iloc[-1])
    bb_upper   = float(df["BB_upper"].iloc[-1])
    bb_lower   = float(df["BB_lower"].iloc[-1])
    bb_mid     = float(df["BB_mid"].iloc[-1])
    bb_pct     = float(df["BB_pct"].iloc[-1])
    bb_width   = float(df["BB_width"].iloc[-1])
    bb_squeeze = int(df["BB_squeeze"].iloc[-1])
    vol_ratio  = float(df["VOL_ratio"].iloc[-1])
    trend      = int(df["EMA_trend"].iloc[-1])
    s_buy      = int(df["Signal_buy"].iloc[-1])
    s_sell     = int(df["Signal_sell"].iloc[-1])

    # Model predictions (use per-ticker scaler)
    lstm_pred,  lstm_prob  = lstm_model.predict_with_scaler(
        model, scaler, df, feature_cols, seq_len, threshold
    )
    arima_pred, arima_fore = arima_model.predict_tomorrow(
        arima_meta, close.tolist(), history_limit=200
    )
    stack_pred, stack_prob = stacking.predict_one_sample(
        meta_model_loaded, lstm_prob, arima_pred
    )

    # Apply BB signal gate logic
    decision = bb_signal_gate(
        s_buy, s_sell,
        lstm_pred, lstm_prob,
        arima_pred,
        stack_pred, stack_prob,
        bb_squeeze,
    )

    # ── Output ────────────────────────────────────────────
    UP   = "UP   📈"
    DOWN = "DOWN 📉"

    print(f"""
{'='*55}
  BB Signal Prediction  [{today.date()}]
{'='*55}
  Ticker        : {ticker}
  Close         : {close_today:.2f} TWD

  -- EMA (context for model, not gate) ----------------
  EMA 20        : {ema20:.2f}
  EMA 60        : {ema60:.2f}
  Trend         : {"Bullish (EMA20 > EMA60)" if trend==1 else "Bearish (EMA20 < EMA60)"}

  -- Bollinger Band [PRIMARY SIGNAL] ------------------
  Upper (2σ)    : {bb_upper:.2f}
  Mid  (MA20)   : {bb_mid:.2f}
  Lower (2σ)    : {bb_lower:.2f}
  BB Width      : {bb_width:.4f}  {"[SQUEEZE]" if bb_squeeze else ""}
  %B Position   : {bb_pct:.2%}  {'(oversold zone)'  if bb_pct <= 0.0 else '(overbought zone)' if bb_pct >= 1.0 else '(normal range)'}
  Touch Lower   : {"YES ★ BUY SIGNAL (close <= lower, oversold)"  if s_buy==1  else "No"}
  Touch Upper   : {"YES ★ SELL SIGNAL (close >= upper, overbought)" if s_sell==1 else "No"}

  -- Volume --------------------------------------------
  Vol Ratio     : {vol_ratio:.2f}x  {"Heavy" if vol_ratio>1.5 else "Normal" if vol_ratio>0.7 else "Light"}

  -- BB Gate (mean reversion) --------------------------
  Buy  Gate     : {"OPEN  ★ (close <= BB lower → oversold)" if s_buy==1  else "CLOSED (price above lower band)"}
  Sell Gate     : {"OPEN  ★ (close >= BB upper → overbought)" if s_sell==1 else "CLOSED (price below upper band)"}
  BB Squeeze    : {"YES  (volatility compressed, breakout may follow)" if bb_squeeze else "No"}

{'='*55}
  Model Predictions  [will BB trade be profitable?]
{'='*55}
  LSTM          : {UP if lstm_pred==1 else DOWN}  (prob={lstm_prob:.2%})
  ARIMA         : {UP if arima_pred==1 else DOWN}  (forecast={arima_fore:.2f})
  Stacking      : {UP if stack_pred==1 else DOWN}  (prob={stack_prob:.2%})

{'='*55}
  Final Decision (BB Signal + Model)
{'='*55}
  Action        : {decision['action']}
  Reason        :
    {decision['reason']}
  Confidence    : {decision['confidence']}

  Disclaimer: For academic research only. Not investment advice.
{'='*55}
    """)

    return {
        "ticker"     : ticker,
        "date"       : str(today.date()),
        "close"      : close_today,
        "signal_buy" : s_buy,
        "signal_sell": s_sell,
        "lstm_pred"  : lstm_pred,
        "lstm_prob"  : lstm_prob,
        "arima_pred" : arima_pred,
        "arima_fore" : arima_fore,
        "stack_pred" : stack_pred,
        "stack_prob" : stack_prob,
        "action"     : decision["action"],
        "confidence" : decision["confidence"],
    }


if __name__ == "__main__":
    result = main()